add auto tag pipe

diff --git a/.github/workflows/dotnet_build.yml b/.github/workflows/dotnet_build.yml
--- a/.github/workflows/dotnet_build.yml
+++ b/.github/workflows/dotnet_build.yml
@@ -45,8 +45,27 @@ jobs:
       working-directory: ./src
 
     - name: Publish NuGet Package
-      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
       env:
         NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
-      run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
+      run: |
+        OUTPUT=$(dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate 2>&1)
+        echo "$OUTPUT"
+
+        if echo "$OUTPUT" | grep -q "already exists at feed"; then
+          echo "NUGET_PUSH_SUCCESS=false" >> $GITHUB_ENV
+        else
+          echo "NUGET_PUSH_SUCCESS=true" >> $GITHUB_ENV
+        fi
       working-directory: ./src
+
+    - name: Create Git Tag
+      if: env.NUGET_PUSH_SUCCESS == 'true'
+      run: |
+        PACKAGE_VERSION=$(ls ./src/nupkg/*.nupkg | grep -oP '\d+\.\d+\.\d+\.\d+' | head -1)
+        if [ -n "$PACKAGE_VERSION" ]; then
+          git tag "v.$PACKAGE_VERSION"
+          git push origin "v.$PACKAGE_VERSION"
+        else
+          echo "Package version could not be determined."
+          exit 1
+        fi
